name: 'tpch_snowflake_project'
version: '1.0.0'
config-version: 2

# This must match the name of the profile in your profiles.yml
profile: 'tpch_snowflake_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tpch_snowflake_project:
    +materialized: view
  staging:
    +materialized: view
  intermediate:
    +materialized: view
  mart:
    +materialized: table
    +schema: mart
  utilities:
    +materialized: table